### ISSUE TITLE
PTDE support?

### ISSUE THREAD

**Issue by Mechapope** [cboyo/DS1Remastered-AutoEquipMod#1]
Hi, would it be possible to add PTDE support to this?

**Comment by cboyo** [comment]
There is a good chance it works by simply changing the name of the process it searches for, from Remastered to PTDE. But I don't have a copy of PTDE to test it properly

**Comment by Mechapope** [comment]
Apologies, I'm a C# guy, I've tried following a few tutorials to compile C++ and I keep getting errors. I could test a version compiled for DARKSOULS.exe or I could give you a download link for PTDE.

**Comment by cboyo** [comment]
I've updated the latests release with a version for PTDE, I've only changed the process name to DARKSOULS.exe
Let me know what happens.

**Comment by Mechapope** [comment]
It finds the process but when scanning to find the signature it says no signatures found.

**Comment by cboyo** [comment]
Then it would requiere a lot more work for it to function correctly. We are talking finding the inventory addresses and how it works     
 which takes some detective work and I don't have that much time rn, Im working in other projects (DS2 randomizer)
If you would like to try to make it work I can answer some questions, if you have any.

**Comment by Mechapope** [comment]
Okay thanks, I'll mess around with it a bit.
